### ISSUE TITLE
Generate GLOSSARY.md?

### ISSUE THREAD

**Issue by audreyt** [pm5/gitbook-plugin-lexicon#2]
我試了一下 clkao 建議的 GLOSSARY.md ( https://github.com/GitbookIO/gitbook#glossary )，在 gitbook build 和 gitbook pdf 都沒有作用，可能是我沒寫好 (看 https://github.com/GitbookIO/gitbook/commit/3a0f00411ba6277bda9dc2be516c96e17ce9db82 應該要會動的 )... 也許還是可以從 json 產生一下。

**Comment by pm5** [comment]
應該在 gitbook 的 package.json 裡加個 script 就可以了。
