### ISSUE TITLE
display at wrong position on mobile view

### ISSUE THREAD

**Issue by yhsiang** [pm5/gitbook-plugin-lexicon#3]
![2015-01-06 04 22 14](https://cloud.githubusercontent.com/assets/93509/5624414/86c419f8-959f-11e4-935b-604f30e19651.png)

**Comment by pm5** [comment]
好像還沒看到 responsive tooltip 有 CSS 解法的⋯⋯待我研究一下

**Comment by pm5** [comment]
改成這樣好了

![screen shot 2015-01-07 at 6 19 21](https://cloud.githubusercontent.com/assets/119645/5644028/f482c688-9699-11e4-8205-50bdd7a69706.png)

![screen shot 2015-01-07 at 6 19 49](https://cloud.githubusercontent.com/assets/119645/5644032/fe0852ae-9699-11e4-9b0a-68842401f1d3.png)

**Comment by pm5** [comment]
寫的亂亂的，改天再參考 https://github.com/dmtintner/scss-tooltips 包一個 package 好了。
